### ISSUE TITLE
Invalid Java object for schema "org.apache.kafka.connect.data.Timestamp" with type INT64

### ISSUE THREAD

**Issue by vdesabou** [rayokota/kafka-connect-jsonata#2]
I'm using avro schema:

```
{
  "fields": [
    {
      "doc": "count",
      "name": "count",
      "type": "long"
    },
    {
      "doc": "First Name of Customer",
      "name": "first_name",
      "type": "string"
    },
    {
      "doc": "Last Name of Customer",
      "name": "last_name",
      "type": "string"
    },
    {
      "doc": "Address of Customer",
      "name": "address",
      "type": "string"
    },
    {
      "name": "createdDate",
      "type": {
        "logicalType": "timestamp-millis",
        "type": "long"
      }
    },
    {
      "default": null,
      "name": "myDecimal",
      "type": [
        "null",
        {
          "logicalType": "decimal",
          "precision": 15,
          "scale": 2,
          "type": "bytes"
        }
      ]
    },
    {
      "default": null,
      "name": "warranty_expiration",
      "type": [
        "null",
        {
          "logicalType": "date",
          "type": "int"
        }
      ]
    }
  ],
  "name": "Customer",
  "namespace": "com.github.vdesabou",
  "type": "record"
}
```

payload:

```
{"count":1,"first_name":"Ernest","last_name":"Olga","address":"Cullen","createdDate":1720912226000,"myDecimal":{"bytes":"\u00021ÕHÏ"},"warranty_expiration":{"int":19920}}
```

And sink connector with

```
    "transforms": "dropTombstone",
    "transforms.dropTombstone.type": "io.yokota.kafka.connect.transform.jsonata.JsonataTransformation",
    "transforms.dropTombstone.expr": "value = null ? null : $"
```

I get

```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:244)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:166)
        at org.apache.kafka.connect.runtime.TransformationChain.transformRecord(TransformationChain.java:74)
        at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:54)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:558)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:509)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:345)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:243)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:212)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:229)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:284)
        at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema "org.apache.kafka.connect.data.Timestamp" with type INT64: class java.lang.String for field: "createdDate"
        at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)
        at org.apache.kafka.connect.data.Struct.put(Struct.java:216)
        at io.yokota.kafka.connect.transform.jsonata.JsonataTransformation.lambda$getObject$6(JsonataTransformation.java:604)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at io.yokota.kafka.connect.transform.jsonata.JsonataTransformation.getObject(JsonataTransformation.java:603)
        at io.yokota.kafka.connect.transform.jsonata.JsonataTransformation.jsonNodeToObject(JsonataTransformation.java:417)
        at io.yokota.kafka.connect.transform.jsonata.JsonataTransformation.jsonNodeToRecord(JsonataTransformation.java:313)
        at io.yokota.kafka.connect.transform.jsonata.JsonataTransformation.apply(JsonataTransformation.java:118)
        at org.apache.kafka.connect.runtime.TransformationStage.apply(TransformationStage.java:57)
        at org.apache.kafka.connect.runtime.TransformationChain.lambda$transformRecord$0(TransformationChain.java:74)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:190)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:224)
        ... 16 more
```

**Comment by rayokota** [comment]
This is now fixed
